// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF2vmcL0cKM4_NyqElWcQqqR86LOP4LTo',
    appId: '1:323538074035:web:ac52606e0523eab4a633c6',
    messagingSenderId: '323538074035',
    projectId: 'safesignal-wits-2026',
    authDomain: 'safesignal-wits-2026.firebaseapp.com',
    storageBucket: 'safesignal-wits-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzD-alMuDlUIfQWVduR6XawXfr2ZuOgqc',
    appId: '1:323538074035:android:52d4c37eeb4bbb7fa633c6',
    messagingSenderId: '323538074035',
    projectId: 'safesignal-wits-2026',
    storageBucket: 'safesignal-wits-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiXGjfCouYq56p5OeRlhEXxF0XC8k1U-o',
    appId: '1:323538074035:ios:e87dd803f41b68a8a633c6',
    messagingSenderId: '323538074035',
    projectId: 'safesignal-wits-2026',
    storageBucket: 'safesignal-wits-2026.firebasestorage.app',
    iosBundleId: 'com.mssdev.safeSignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiXGjfCouYq56p5OeRlhEXxF0XC8k1U-o',
    appId: '1:323538074035:ios:e87dd803f41b68a8a633c6',
    messagingSenderId: '323538074035',
    projectId: 'safesignal-wits-2026',
    storageBucket: 'safesignal-wits-2026.firebasestorage.app',
    iosBundleId: 'com.mssdev.safeSignal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF2vmcL0cKM4_NyqElWcQqqR86LOP4LTo',
    appId: '1:323538074035:web:59815702244245dfa633c6',
    messagingSenderId: '323538074035',
    projectId: 'safesignal-wits-2026',
    authDomain: 'safesignal-wits-2026.firebaseapp.com',
    storageBucket: 'safesignal-wits-2026.firebasestorage.app',
  );
}
